name: Build and Deploy Docker Image

on:
  push:
    branches:
      - MOODLE_403_STABLE

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t daisyjabbour/moodle:latest .

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push Docker image
      run: docker push daisyjabbour/moodle:latest

    - name: executing remote ssh commands
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.PORT }}
        script: sudo docker pull daisyjabbour/moodle:latest && sudo docker run -d -p 80:80 --name moodle  daisyjabbour/moodle:latest

            
