name: Build and Push Docker image

on:
  push:
    branches:
      - MOODLE_403_STABLE

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: daisyjabbour/moodle:latest

    - name: Build PostgreSQL container
      run: |
        docker build -t daisyjabbour/postgresql:latest - <<EOF
        FROM postgres:latest
        RUN sudo -u postgres psql -c "CREATE USER moodleuser WITH PASSWORD '123';"
        RUN sudo -u postgres psql -c "CREATE DATABASE moodle WITH OWNER moodleuser;"
        EOF

    - name: Push PostgreSQL container
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: daisyjabbour/postgresql:latest

    - name: Execute remote SSH commands
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          sudo docker pull daisyjabbour/moodle:latest
          sudo docker pull daisyjabbour/postgresql:latest
          sudo docker run -d -p 82:80 --name moodle-db daisyjabbour/postgresql:latest
          sudo docker exec -it moodle-db sudo -u postgres psql -c "CREATE USER moodleuser WITH PASSWORD '123';"
          sudo docker exec -it moodle-db sudo -u postgres psql -c "CREATE DATABASE moodle WITH OWNER moodleuser;"
